#!/bin/bash
#SBATCH -t 10:00:00
#SBATCH -A
#SBATCH -p
#SBATCH --mem=32000
#SBATCH -J train_vae
#SBATCH --mail-type=None
#SBATCH -o train_vae-%A.%a.output
#SBATCH -e train_vae-%A.%a.error
#SBATCH -n 1 #number of tasks
#SBATCH -c 1 #number of cores (use more for multithreading)


# Load required modules
module load lib/TensorFlow/2.6.0-foss-2021a-CUDA-11.3.1
module load vis/matplotlib/3.4.2-foss-2021a

# Assign arguments to variables
animal="$1"
animal_no_noise="$2"



srun python simple_analyse_sync.py --animal "$animal" --animal_no_noise "$animal_no_noise"